### ISSUE TITLE
Can I use the tool without sleep stage file? or is there any implementation of A2 to 5 that is open-source?

### ISSUE THREAD

**Issue by mqhu** [swarby/A7_LacourseSpindleDetector#1]
Hi, I'm trying to find a tool to detect spindles in EEG but I haven't got corresponding sleep stage files. I'm wondering if sleep stage file is a must for your toolbox.
If so, I'd appreciate it if you'd tell me where to find the implemention of A2 to 5 detectors.
Thanks!

**Comment by klacourse** [comment]
Hi,
I'm happy to know that you are interested by our tools. A7 can be used
without any sleep staging. Just provide consistent inputs to the detector.
If it is not clear in the readme, let me know I'll add information to it.

A2 to a5 are available here
https://github.com/swarby/SpindleAlgorithms_NatMeth_2014

Regards,

Karine
